---
title: "DSSI Challenge Problem Task 1"
author: "Sucheen Sundaram"
date: '2022-06-30'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(tidymodels)
library(glmnet)
library(discrim)
library(rpart)
library(rpart.plot)
library(baguette)
train$label <- as.factor(train$label)
test$label <- as.factor(test$label)
validation$label <- as.factor(validation$label)
```

```{r}
df <- read_csv("mpro_exp_data2_rdkit_feat.csv")
train <- filter(df, subset == "train")
validation <- filter(df, subset == "valid")
test <- filter(df, subset == "test")
train$smiles <- as.factor(train$smiles)

train <- select(train, -c(X1, lib_name, cmpd_id, subset))
validation <- validation[colnames(train)]
test <- test[colnames(train)]

train$label <- as.factor(train$label)
test$label <- as.factor(test$label)
validation$label <- as.factor(validation$label)

for(i in colnames(train)) {
  vec <- train[,i] %>%
    pluck(i)
  non_null <- vec[!is.na(vec)]
  if(length(non_null) != 0) {
      null <- vec[is.na(vec) | is.nan(vec) | is.infinite(vec)]
    rand_sample <- sample(non_null, length(null), replace = TRUE)
    vec[is.na(vec)] <- rand_sample
    train[,i] <- vec %>%
      data.frame()
  }else{
    train[,i] <- 0 %>%
      rep(nrow(train)) %>%
      data.frame()
  }
}
train <- filter_all(train, all_vars(is.finite(.) & !is.na(.)))
train <- distinct(train)
```

```{r}
train %>%
  select_if(is.numeric) %>%
  cor() %>%
  data.frame()
```


```{r}
train$label <- as.factor(train$label)
test$label <- as.factor(test$label)
validation$label <- as.factor(validation$label)

train[is.na(train) | train == NaN | train == Inf] %>% length()

for(i in colnames(train)) {
  tryCatch(expr = {
    train[i] <- train[i] %>% pluck(i) %>% as.double() %>% data.frame()
  }, error = function(e) {
    
  })
}

check <- function(col) {
  return(all(is.finite(col)))
}
train <- select(train, -c(feat_10))

recString <- "label ~"
i <- 1
for(col in colnames(train)[colnames(train) != "label"]) {
  if(i == 1) {
    recString <- paste(recString, col)
  }else{
    recString <- paste(recString, col, sep = "+")
  }
  #print(as.formula(recString))
  tryCatch(expr = {
    for_recipe <- recipe(as.formula(recString), data = train) %>%
      step_dummy(all_nominal_predictors()) %>%
      step_normalize(all_numeric_predictors()) %>%
      step_pca(all_numeric(), threshold = 0.90)
    workflow() %>%
    add_recipe(for_recipe) %>%
    add_model(logit_mod) %>%
    fit_resamples(cv) %>%
    collect_metrics() %>%
    mutate(rec = recString) %>%
    print()
  }, error = function(e) {
    print(recString)
    print("Error")
    break
  }, warning = function(w) {
    print(recString)
    print("Warning")
  })
  i <- i+1
}

rec <- recipe(label ~ ., data = train) %>%
      step_dummy(all_nominal_predictors()) %>%
      step_normalize(all_numeric_predictors()) %>%
      step_pca(all_numeric(), threshold = 0.90)

```

```{r}
rec <- recipe(label ~ ., data = train) %>%
  remove_role(smiles, old_role = "predictor") %>%
  step_dummy(all_nominal_predictors()) %>%
  step_normalize(all_numeric_predictors()) %>%
  step_pca(all_numeric(), threshold = 0.90)
cv <- vfold_cv(train, 15)
logit_mod <- logistic_reg() %>%
  set_engine("glm") %>%
  set_mode("classification")
work <- workflow() %>%
  add_recipe(rec) %>%
  add_model(logit_mod)
work %>%
  fit_resamples(cv) %>%
  collect_metrics()
model <- fit(work, train)
roc <- test %>%
  cbind(predict(model, test, type = "prob")) %>%
  roc_curve(truth = label, estimate = .pred_0)
roc
ggplot(roc) + geom_line(aes(x=1-specificity, y=sensitivity))

```



```{r}
for(i in colnames(validation)) {
  vec <- validation[,i] %>%
    pluck(i)
  non_null <- vec[!is.na(vec)]
  if(length(non_null) != 0) {
      null <- vec[is.na(vec) | is.nan(vec) | is.infinite(vec)]
    rand_sample <- sample(non_null, length(null), replace = TRUE)
    vec[is.na(vec)] <- rand_sample
    validation[,i] <- vec %>%
      data.frame()
  }
}
```

KNN
```{r}
knn_mod <- nearest_neighbor() %>%
  set_engine("kknn") %>%
  set_mode("classification")
work <- workflow() %>%
  add_recipe(rec) %>%
  add_model(knn_mod)
work %>%
  fit_resamples(cv) %>%
  collect_metrics()

knn_mod <- nearest_neighbor(neighbors = tune()) %>%
  set_engine("kknn") %>%
  set_mode("classification")
work <- workflow() %>%
  add_recipe(rec) %>%
  add_model(knn_mod)
grid <- grid_regular(
  neighbors(c(1, 20)),
  levels = 15
)
tun_grid <- tune_grid(work, cv, grid)
tun_grid %>%
  collect_metrics() %>%
  filter(.metric == "accuracy") %>%
  slice_max(mean)

knn_mod <- nearest_neighbor(neighbors = 5) %>%
  set_engine("kknn") %>%
  set_mode("classification")
work <- workflow() %>%
  add_recipe(rec) %>%
  add_model(knn_mod) %>%
  fit(train)
work %>%
  predict(test) %>%
  cbind(test) %>%
  accuracy(truth = label, estimate = .pred_class)
work %>%
  predict(validation) %>%
  cbind(validation) %>%
  accuracy(truth = label, estimate = .pred_class)
  


predict(work, validation[33,])
```

Decision Tree Classifier
```{r}
tree_mod <- decision_tree() %>%
  set_engine("rpart") %>%
  set_mode("classification")

work <- workflow() %>%
  add_recipe(rec) %>%
  add_model(tree_mod)
work %>%
  fit_resamples(cv) %>%
  collect_metrics()

work %>%
  fit(train) %>%
  extract_fit_parsnip() %>%
  pluck("fit") %>%
  rpart.plot()

work %>%
  fit(train) %>%
  predict(test) %>%
  cbind(test) %>%
  accuracy(truth = label, estimate = .pred_class)

work %>%
  fit(train) %>%
  predict(validation) %>%
  cbind(validation) %>%
  accuracy(truth = label, estimate = .pred_class)

work %>%
  fit(train) %>%
  predict(validation) %>%
  cbind(validation) %>%
  conf_mat(truth = label, estimate = .pred_class)
```

Bagged Tree
```{r}
bagged_tree_mod <- bag_tree() %>%
  set_engine("rpart", times = 5) %>%
  set_mode("classification")
work <- workflow() %>%
  add_recipe(rec) %>%
  add_model(bagged_tree_mod)
work %>%
  fit_resamples(cv) %>%
  collect_metrics()

work %>%
  fit(train) %>%
  predict(test) %>%
  cbind(test) %>%
  accuracy(truth = label, estimate = .pred_class)

work %>%
  fit(train) %>%
  predict(validation) %>%
  cbind(validation) %>%
  accuracy(truth = label, estimate = .pred_class)

bagged_tree_mod <- bag_tree(cost_complexity = tune(), tree_depth = tune(), min_n = tune()) %>%
  set_engine("rpart", times = 5) %>%
  set_mode("classification")
work <- workflow() %>%
  add_recipe(rec) %>%
  add_model(bagged_tree_mod)
grid <- grid_regular(
  cost_complexity(),
  tree_depth(c(1, 10)),
  min_n(c(1, ncol(train))),
  levels = 5
)
tuned <- tune_grid(work, cv, grid)
best_model_spec <- tuned %>%
  collect_metrics() %>%
  filter(.metric == "accuracy") %>%
  slice_max(mean)
best_model_spec

best_bagged_mod <- bag_tree(cost_complexity = best_model_spec$cost_complexity[1], tree_depth = best_model_spec$tree_depth[1], min_n = best_model_spec$min_n[1]) %>%
  set_engine("rpart", times = 5) %>%
  set_mode("classification")
work <- workflow() %>%
  add_recipe(rec) %>%
  add_model(best_bagged_mod) %>%
  fit(train)
work %>%
  fit(train) %>%
  predict(test) %>%
  cbind(test) %>%
  accuracy(truth = label, estimate = .pred_class)
work %>%
  fit(train) %>%
  predict(validation) %>%
  cbind(validation) %>%
  accuracy(truth = label, estimate = .pred_class)
```

Logistic Ridge Regression
```{r}
ridge_mod <- logistic_reg(penalty = 0.01, mixture = 0.9) %>%
  set_engine("glm") %>%
  set_mode("classification")
work <- workflow() %>%
  add_recipe(rec) %>%
  add_model(ridge_mod)
work %>%
  fit_resamples(cv) %>%
  collect_metrics()
work <- work %>%
  fit(train)

work %>%
  predict(test) %>%
  cbind(test) %>%
  accuracy(truth = label, estimate = .pred_class)

work %>%
#  fit(train) %>%
  predict(validation) %>%
  cbind(validation) %>%
  accuracy(truth = label, estimate = .pred_class)

work %>%
  fit(train) %>%
  predict(test) %>%
  cbind(test) %>%
  conf_mat(truth = label, estimate = .pred_class)


ridge_mod <- logistic_reg(penalty = tune(), mixture = tune()) %>%
  set_engine("glm") %>%
  set_mode("classification")
grid <- grid_regular(
  penalty(),
  mixture(),
  levels = 10
)
work <- workflow() %>%
  add_recipe(rec) %>%
  add_model(ridge_mod)
tuned <- tune_grid(work, cv, grid)
best_specs <- tuned %>%
  collect_metrics() %>%
  filter(.metric == "accuracy") %>%
  slice_max(mean)
best_specs
ridge_mod <- logistic_reg(penalty = best_specs$penalty, mixture = best_specs$mixture) %>%
  set_engine("glm") %>%
  set_mode("classification")
work <- workflow() %>%
  add_recipe(rec) %>%
  add_model(ridge_mod) %>%
  fit(train)
work %>%
  tidy() %>%
  filter(estimate != 0)
```

Random Forest
```{r}
forest_train <- sample_n(train, 20)
forest_rec <- recipe(label ~ ., data = forest_train) %>%
  remove_role(smiles, old_role = "predictor") %>%
  step_dummy(all_nominal_predictors()) %>%
  step_normalize(all_numeric_predictors()) %>%
  step_pca(all_numeric(), threshold = 0.90)
forest_mod <- rand_forest(trees = 5) %>%
  set_engine("ranger") %>%
  set_mode("classification")
forest_cv <- vfold_cv(forest_train, 10)
work <- workflow() %>%
  add_recipe(forest_rec) %>%
  add_model(forest_mod)
work %>%
  fit_resamples(cv) %>%
  collect_metrics()
work <- work %>%
  fit(train)

work %>%
  predict(test) %>%
  cbind(test) %>%
  accuracy(truth = label, estimate = .pred_class)

work %>%
  predict(validation) %>%
  cbind(validation) %>%
  accuracy(truth = label, estimate = .pred_class)

work %>%
  fit(train) %>%
  predict(test) %>%
  cbind(test) %>%
  conf_mat(truth = label, estimate = .pred_class)
```


Neural Network
```{r}
nn_mod <- mlp(hidden_units = 3, epochs = 10, activation = "linear") %>%
  set_engine("keras") %>%
  set_mode("classification")
work <- workflow() %>%
  add_recipe(rec) %>%
  add_model(nn_mod)
work %>%
  fit_resamples(cv) %>%
  collect_metrics()
work <- work %>%
  fit(train)

work %>%
  predict(test) %>%
  cbind(test) %>%
  accuracy(truth = label, estimate = .pred_class)

work %>%
#  fit(train) %>%
  predict(validation) %>%
  cbind(validation) %>%
  accuracy(truth = label, estimate = .pred_class)


nn_mod <- mlp(hidden_units = tune(), epochs = 20, activation = "linear") %>%
  set_engine("keras") %>%
  set_mode("classification")
grid <- grid_regular(
  hidden_units(c(1, 3)),
  levels = 3
)
work <- workflow() %>%
  add_recipe(rec) %>%
  add_model(nn_mod)
tun_grid <- tune_grid(work, cv, grid)
tun_grid %>%
  collect_metrics() %>%
  filter(.metric == "accuracy") %>%
  slice_max(mean)

activation_tune <- mlp(hidden_units = 8, epochs = 20, activation = tune()) %>%
  set_engine("keras") %>% 
  set_mode("classification")
activation_grid <- data.frame(activation = c("linear", "relu", "elu", "tanh", "softmax"))
activation_work <- workflow() %>%
  add_recipe(rec) %>%
  add_model(activation_tune)
activation_metrics <- tune_grid(activation_work, cv, activation_grid)
activation_metrics %>%
  collect_metrics() %>%
  filter(.metric == "accuracy") %>%
  slice_max(mean)


nn_mod <- mlp(hidden_units = 8, epochs = tune(), activation = "linear") %>%
  set_engine("keras") %>%
  set_mode("classification")
grid <- grid_regular(
  epochs(c(10, 120)),
  levels = 5
)
work <- workflow() %>%
  add_recipe(rec) %>%
  add_model(nn_mod)
tun_grid <- tune_grid(work, cv, grid)
tun_grid %>%
  collect_metrics() %>%
  filter(.metric == "accuracy") %>%
  slice_max(mean)

nn_final <- mlp(hidden_units = 10, epochs = 50, activation = "softmax") %>% # final model
  set_engine("keras") %>%
  set_mode("classification")
nn_final_work <- workflow() %>%
  add_recipe(rec) %>%
  add_model(nn_final) %>%
  fit(train)
nn_final_work %>%
  predict(test) %>%
  cbind(test) %>%
  accuracy(truth = label, estimate = .pred_class) %>%
  mutate(count = .estimate*nrow(test), n = nrow(test), .estimate = round(.estimate, 3))

nn_final_work %>%
  predict(validation) %>%
  cbind(validation) %>%
  accuracy(truth = label, estimate = .pred_class) %>%
  mutate(count = .estimate*nrow(validation), n = nrow(validation))
```

SVC
```{r}
svm_spec <- svm_poly(degree = 1) %>%
  set_mode("classification") %>%
  set_engine("kernlab")
work <- workflow() %>%
  add_recipe(rec) %>%
  add_model(svm_spec)
work %>%
  fit_resamples(cv) %>%
  collect_metrics()

work %>%
  fit(train) %>%
  predict(test) %>%
  cbind(test) %>%
  accuracy(truth = label, estimate = .pred_class) %>%
  mutate(.estimate = round(.estimate, 3))
```

